#!/usr/bin/env python3
"""Minimal RFC 2136 DNS UPDATE server with TSIG auth for dnsmasq.

Listens on UPDATE_PORT (default 5353). Validates TSIG, applies A/AAAA/TXT/CNAME/PTR
changes to an in-memory zone (forward ``example.com`` and reverse
``0.168.192.in-addr.arpa``), renders dnsmasq conf, and signals dnsmasq.
"""

from __future__ import annotations

import json
import os
import re
import signal
import socket
import socketserver
import sys
import threading
from pathlib import Path
from typing import Any

import dns.exception
import dns.flags
import dns.message
import dns.name
import dns.rcode
import dns.rdatatype
import dns.tsig
import dns.tsigkeyring
import dns.update

ZONE = os.environ.get("DDNS_ZONE", "example.com")
REV_ZONE = os.environ.get("DDNS_REV_ZONE", "0.168.192.in-addr.arpa")
LISTEN_ADDR = os.environ.get("DDNS_LISTEN", "0.0.0.0")
LISTEN_PORT = int(os.environ.get("DDNS_PORT", "5353"))
KEY_NAME = os.environ.get("DDNS_KEY_NAME", "update-key")
KEY_FILE = Path(os.environ.get("DDNS_KEY_FILE", "/keys/update.key"))
STATE_FILE = Path(os.environ.get("DDNS_STATE_FILE", "/data/zone.json"))
CONF_FILE = Path(os.environ.get("DDNS_CONF_FILE", "/data/dynamic.conf"))
HOSTS_FILE = Path(os.environ.get("DDNS_HOSTS_FILE", "/data/dynamic.hosts"))
DNSMASQ_PID_FILE = Path(os.environ.get("DNSMASQ_PID_FILE", "/run/dnsmasq.pid"))
TTL_DEFAULT = int(os.environ.get("DDNS_TTL", "300"))

_lock = threading.Lock()
_zone: dict[str, list[dict[str, Any]]] = {}
_keyring = None
_keyname = None


def log(msg: str) -> None:
    """Print a timestamped-style log line to stdout (flushed immediately)."""
    print(f"[ddnsd] {msg}", flush=True)


def parse_key_file(path: Path) -> tuple[dns.name.Name, dns.tsigkeyring.Keyring]:
    """Parse a named.conf-style TSIG key file into a key name and keyring.

    Expects a ``key "name" { algorithm ...; secret "..."; };`` block.
    Prefers ``dns.tsig.Key`` when available so the HMAC algorithm is preserved.
    """
    text = path.read_text()
    name_m = re.search(r'key\s+"?([^"{\s]+)"?\s*\{', text)
    algo_m = re.search(r"algorithm\s+([^;]+);", text)
    secret_m = re.search(r'secret\s+"([^"]+)";', text)
    if not (name_m and algo_m and secret_m):
        raise ValueError(f"Could not parse TSIG key file: {path}")

    name = dns.name.from_text(name_m.group(1))
    algo_raw = algo_m.group(1).strip().lower().replace("_", "-")
    algo_map = {
        "hmac-sha256": dns.tsig.HMAC_SHA256,
        "hmac-sha224": dns.tsig.HMAC_SHA224,
        "hmac-sha384": dns.tsig.HMAC_SHA384,
        "hmac-sha512": dns.tsig.HMAC_SHA512,
        "hmac-sha1": dns.tsig.HMAC_SHA1,
        "hmac-md5": dns.tsig.HMAC_MD5,
    }
    if algo_raw not in algo_map:
        raise ValueError(f"Unsupported TSIG algorithm: {algo_raw}")

    keyring = dns.tsigkeyring.from_text({name.to_text(): secret_m.group(1)})
    # dnspython keyring values need algorithm association via Keyring with algorithms
    # Use dns.tsig.Key for modern dnspython
    try:
        from dns.tsig import Key

        key = Key(name, secret_m.group(1), algorithm=algo_map[algo_raw])
        return name, {name: key}
    except Exception:
        return name, keyring


def load_state() -> None:
    """Load the persisted zone dictionary from ``STATE_FILE`` into ``_zone``."""
    global _zone
    if STATE_FILE.exists():
        _zone = json.loads(STATE_FILE.read_text() or "{}")
    else:
        _zone = {}


def save_state() -> None:
    """Persist ``_zone`` to ``STATE_FILE`` as sorted, indented JSON."""
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(_zone, indent=2, sort_keys=True) + "\n")


def is_wildcard_owner(owner: str) -> bool:
    """Return True if ``owner`` is a DNS wildcard name (``*.suffix``)."""
    return owner.startswith("*.") and len(owner) > 2


def wildcard_suffix(owner: str) -> str:
    """Strip the leading ``*.`` from a wildcard owner name."""
    return owner[2:]


def render_dnsmasq_files() -> bool:
    """Render ``_zone`` into dnsmasq hosts and conf drop-in files.

    Ordinary A/AAAA records go to ``HOSTS_FILE`` (forward + reverse via hosts).
    Wildcard A/AAAA (``*.suffix``) become ``address=/suffix/ip`` in ``CONF_FILE``,
    because dnsmasq does not honor ``*`` in hosts files. TXT/CNAME/PTR also go
    to ``CONF_FILE``.

    Returns:
        True if ``CONF_FILE`` content changed (dnsmasq must be restarted to
        re-read conf-file); False if only hosts need a SIGHUP reload.
    """
    hosts_lines = [
        "# Auto-generated by ddnsd — do not edit",
        f"# Zone: {ZONE} (A/AAAA; reverse via hosts for {REV_ZONE})",
        "",
    ]
    conf_lines = [
        "# Auto-generated by ddnsd — do not edit",
        f"# Zones: {ZONE}, {REV_ZONE} (TXT/CNAME/PTR + wildcard address=)",
        "",
    ]
    address_map: dict[str, list[str]] = {}
    wildcard_suffixes: set[str] = set()
    for owner, rrs in sorted(_zone.items()):
        for rr in rrs:
            rtype = rr["type"]
            data = rr["data"]
            if rtype in {"A", "AAAA"}:
                if is_wildcard_owner(owner):
                    # dnsmasq: address=/apps.example.com/IP answers for that
                    # name and all names under it (covers *.apps.example.com).
                    suffix = wildcard_suffix(owner)
                    conf_lines.append(f"address=/{suffix}/{data}")
                    wildcard_suffixes.add(suffix)
                else:
                    address_map.setdefault(data, [])
                    if owner not in address_map[data]:
                        address_map[data].append(owner)
            elif rtype == "TXT":
                safe = data.replace('"', "")
                conf_lines.append(f'txt-record={owner},"{safe}"')
            elif rtype == "CNAME":
                target = data.rstrip(".")
                conf_lines.append(f"cname={owner},{target}")
            elif rtype == "PTR":
                target = data.rstrip(".")
                # dnsmasq wants the reverse name without a trailing dot.
                conf_lines.append(f"ptr-record={owner},{target}")
            else:
                conf_lines.append(f"# unsupported {rtype} {owner} {data}")

    # With local=/<zone>/, IPv4-only address=/suffix/ip makes AAAA queries
    # return NXDOMAIN (nslookup then prints a false failure after a good A).
    # Pair each wildcard with :: so AAAA is NOERROR. Clients should still use A.
    for suffix in sorted(wildcard_suffixes):
        conf_lines.append(f"address=/{suffix}/::")

    for ip, names in sorted(address_map.items()):
        hosts_lines.append(f"{ip} {' '.join(names)}")

    HOSTS_FILE.parent.mkdir(parents=True, exist_ok=True)
    old_conf = CONF_FILE.read_text() if CONF_FILE.exists() else ""
    new_hosts = "\n".join(hosts_lines) + "\n"
    new_conf = "\n".join(conf_lines) + "\n"
    HOSTS_FILE.write_text(new_hosts)
    CONF_FILE.write_text(new_conf)
    return old_conf != new_conf


def reload_dnsmasq(restart: bool) -> None:
    """Signal the running dnsmasq process to pick up rewritten zone files.

    Args:
        restart: If True, send SIGTERM so the entrypoint restarts dnsmasq
            (needed for conf-file changes). If False, send SIGHUP to reload
            ``addn-hosts`` only.
    """
    if not DNSMASQ_PID_FILE.exists():
        log("dnsmasq pid file missing; files written but not reloaded")
        return
    pid = int(DNSMASQ_PID_FILE.read_text().strip())
    if restart:
        os.kill(pid, signal.SIGTERM)
        log(f"sent SIGTERM to dnsmasq pid {pid} (reload conf-file)")
    else:
        os.kill(pid, signal.SIGHUP)
        log(f"sent SIGHUP to dnsmasq pid {pid} (reload hosts)")


def owner_in_zone(name: dns.name.Name) -> bool:
    """Return True if ``name`` belongs to the forward or reverse lab zone."""
    forward = dns.name.from_text(ZONE)
    reverse = dns.name.from_text(REV_ZONE)
    return (
        name.is_subdomain(forward)
        or name == forward
        or name.is_subdomain(reverse)
        or name == reverse
    )


def apply_update(msg: dns.message.Message) -> int:
    """Apply an RFC 2136 UPDATE message to the in-memory ``_zone``.

    Message layout: question = zone, answer = prerequisites,
    authority = updates. Accepts the forward zone or ``REV_ZONE``.
    Mutates ``_zone`` in place on success. A/AAAA reverse lookups are
    served from the hosts file; explicit PTR updates are also supported.

    Returns:
        A DNS rcode integer (e.g. ``NOERROR``, ``NOTAUTH``, ``REFUSED``).
    """
    import dns.rdataclass

    forward = dns.name.from_text(ZONE)
    reverse = dns.name.from_text(REV_ZONE)
    if not msg.question:
        return dns.rcode.FORMERR
    qname = msg.question[0].name
    if qname not in (forward, reverse):
        return dns.rcode.NOTAUTH

    for rrset in msg.answer:  # prerequisites
        owner = rrset.name.to_text().rstrip(".")
        if rrset.rdtype == dns.rdatatype.ANY and len(rrset) == 0 and rrset.rdclass == dns.rdataclass.ANY:
            if owner in _zone and _zone[owner]:
                return dns.rcode.YXDOMAIN
        elif len(rrset) == 0 and rrset.rdclass == dns.rdataclass.NONE:
            rtype = dns.rdatatype.to_text(rrset.rdtype)
            existing = [r for r in _zone.get(owner, []) if r["type"] == rtype]
            if existing:
                return dns.rcode.YXRRSET
        elif rrset.rdtype == dns.rdatatype.ANY and len(rrset) == 0:
            if owner not in _zone or not _zone[owner]:
                return dns.rcode.NXDOMAIN
        elif len(rrset) == 0:
            rtype = dns.rdatatype.to_text(rrset.rdtype)
            existing = [r for r in _zone.get(owner, []) if r["type"] == rtype]
            if not existing:
                return dns.rcode.NXRRSET

    for rrset in msg.authority:  # updates
        if not owner_in_zone(rrset.name):
            return dns.rcode.NOTZONE
        owner = rrset.name.to_text().rstrip(".")
        rtype = dns.rdatatype.to_text(rrset.rdtype)

        # dnspython often decodes UPDATE deletes as class IN with ttl=0, while
        # the wire format uses CLASS ANY (delete) or NONE (delete rdata).
        wire_delete_all = rrset.rdclass == dns.rdataclass.ANY and rrset.rdtype == dns.rdatatype.ANY
        decoded_delete_all = (
            rrset.rdtype == dns.rdatatype.ANY and len(rrset) == 0 and rrset.ttl == 0
        )
        wire_delete_rrset = (
            rrset.rdclass == dns.rdataclass.ANY
            and rrset.rdtype != dns.rdatatype.ANY
            and len(rrset) == 0
        )
        decoded_delete_rrset = (
            rrset.rdclass == dns.rdataclass.IN
            and rrset.rdtype != dns.rdatatype.ANY
            and len(rrset) == 0
            and rrset.ttl == 0
        )
        wire_delete_rdata = rrset.rdclass == dns.rdataclass.NONE
        decoded_delete_rdata = (
            rrset.rdclass == dns.rdataclass.IN and len(rrset) > 0 and rrset.ttl == 0
        )

        # Delete all RRsets for name: ``update delete name``
        if wire_delete_all or decoded_delete_all:
            _zone.pop(owner, None)
            continue

        # Delete an RRset: ``update delete name A``
        if wire_delete_rrset or decoded_delete_rrset:
            _zone[owner] = [r for r in _zone.get(owner, []) if r["type"] != rtype]
            if not _zone[owner]:
                _zone.pop(owner, None)
            continue

        # Delete specific rdata: ``update delete name A 192.0.2.1``
        if wire_delete_rdata or decoded_delete_rdata:
            for rdata in rrset:
                data = rdata_to_text(rtype, rdata)
                _zone[owner] = [
                    r for r in _zone.get(owner, []) if not (r["type"] == rtype and r["data"] == data)
                ]
            if owner in _zone and not _zone[owner]:
                _zone.pop(owner, None)
            continue

        # Add records: ``update add name ttl type rdata``
        if rtype not in {"A", "AAAA", "TXT", "CNAME", "PTR"}:
            return dns.rcode.REFUSED

        bucket = _zone.setdefault(owner, [])
        for rdata in rrset:
            data = rdata_to_text(rtype, rdata)
            if rtype in {"CNAME", "PTR"}:
                bucket[:] = [r for r in bucket if r["type"] != rtype]
            else:
                bucket[:] = [r for r in bucket if not (r["type"] == rtype and r["data"] == data)]
            bucket.append({"type": rtype, "data": data, "ttl": rrset.ttl or TTL_DEFAULT})

    return dns.rcode.NOERROR


def rdata_to_text(rtype: str, rdata: Any) -> str:
    """Convert a dnspython rdata object to the text form stored in ``_zone``."""
    if rtype == "TXT":
        # Combine TXT strings
        return "".join(s.decode("utf-8") if isinstance(s, bytes) else str(s) for s in rdata.strings)
    if rtype in {"CNAME", "PTR"}:
        target = getattr(rdata, "target", None) or getattr(rdata, "ptrdname", None)
        if target is not None:
            return target.to_text().rstrip(".")
        return str(rdata).rstrip(".")
    return rdata.address if hasattr(rdata, "address") else str(rdata)


def handle_wire(data: bytes, peer: str) -> bytes:
    """Parse, authenticate, and process one DNS wire-format message.

    Requires a valid TSIG signature for UPDATE opcodes. On success, persists
    state, renders dnsmasq files, and reloads dnsmasq.

    Args:
        data: Raw DNS message bytes from the client.
        peer: Client address string used only for logging.

    Returns:
        Wire-format response bytes, or empty bytes if the request is unusable.
    """
    try:
        msg = dns.message.from_wire(data, keyring=_keyring)
    except dns.tsig.PeerBadKey:
        log(f"bad TSIG key from {peer}")
        resp = dns.message.make_response(dns.message.from_wire(data, ignore_trailing=True))
        resp.set_rcode(dns.rcode.NOTAUTH)
        return resp.to_wire()
    except dns.tsig.PeerBadSignature:
        log(f"bad TSIG signature from {peer}")
        resp = dns.message.make_response(dns.message.from_wire(data, ignore_trailing=True))
        resp.set_rcode(dns.rcode.NOTAUTH)
        return resp.to_wire()
    except dns.exception.FormError:
        log(f"form error from {peer}")
        return b""
    except Exception as exc:
        log(f"parse error from {peer}: {exc}")
        return b""

    if msg.opcode() != dns.opcode.UPDATE:
        resp = dns.message.make_response(msg)
        resp.set_rcode(dns.rcode.REFUSED)
        if msg.had_tsig:
            resp.use_tsig(_keyring, keyname=_keyname)
        return resp.to_wire()

    if not msg.had_tsig:
        log(f"rejected unsigned UPDATE from {peer}")
        resp = dns.message.make_response(msg)
        resp.set_rcode(dns.rcode.REFUSED)
        return resp.to_wire()

    with _lock:
        load_state()
        rcode = apply_update(msg)
        if rcode == dns.rcode.NOERROR:
            save_state()
            restart = render_dnsmasq_files()
            reload_dnsmasq(restart=restart)
            log(f"UPDATE ok from {peer}")
        else:
            log(f"UPDATE failed from {peer}: {dns.rcode.to_text(rcode)}")

    resp = dns.message.make_response(msg)
    resp.set_rcode(rcode)
    resp.use_tsig(_keyring, keyname=_keyname)
    return resp.to_wire()


class UDPHandler(socketserver.BaseRequestHandler):
    def handle(self) -> None:
        """Handle one UDP DNS datagram and send the response to the peer."""
        data, sock = self.request
        peer = f"{self.client_address[0]}:{self.client_address[1]}"
        out = handle_wire(data, peer)
        if out:
            sock.sendto(out, self.client_address)


class TCPHandler(socketserver.BaseRequestHandler):
    def handle(self) -> None:
        """Handle one length-prefixed TCP DNS message and write the response."""
        peer = f"{self.client_address[0]}:{self.client_address[1]}"
        sock = self.request
        hdr = sock.recv(2)
        if len(hdr) < 2:
            return
        length = int.from_bytes(hdr, "big")
        data = b""
        while len(data) < length:
            chunk = sock.recv(length - len(data))
            if not chunk:
                return
            data += chunk
        out = handle_wire(data, peer)
        if out:
            sock.sendall(len(out).to_bytes(2, "big") + out)


class ThreadedUDPServer(socketserver.ThreadingMixIn, socketserver.UDPServer):
    allow_reuse_address = True
    daemon_threads = True


class ThreadedTCPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    allow_reuse_address = True
    daemon_threads = True


def main() -> int:
    """Load the TSIG key and zone state, then serve UPDATE on UDP and TCP.

    Returns:
        ``1`` if the key file is missing; otherwise runs until interrupted
        (``serve_forever`` does not return under normal operation).
    """
    global _keyring, _keyname

    if not KEY_FILE.exists():
        log(f"TSIG key file not found: {KEY_FILE}")
        log("Run scripts/generate-tsig-key.sh on the host first.")
        return 1

    _keyname, _keyring = parse_key_file(KEY_FILE)
    # Prefer env key name if it matches
    env_name = dns.name.from_text(KEY_NAME)
    if env_name in _keyring:
        _keyname = env_name

    load_state()
    render_dnsmasq_files()
    log(f"loaded {sum(len(v) for v in _zone.values())} records for zone {ZONE}")
    log(f"listening on {LISTEN_ADDR}:{LISTEN_PORT}/udp+tcp (TSIG key {_keyname})")

    udp = ThreadedUDPServer((LISTEN_ADDR, LISTEN_PORT), UDPHandler)
    tcp = ThreadedTCPServer((LISTEN_ADDR, LISTEN_PORT), TCPHandler)

    threading.Thread(target=udp.serve_forever, daemon=True).start()
    tcp.serve_forever()
    return 0


if __name__ == "__main__":
    sys.exit(main())
